### ISSUE TITLE
f-droid’s new builds, please!

### ISSUE THREAD

**Issue by DI555** [AnySoftKeyboard/AnySoftKeyboard#3729]
please, provide f-droid’s builds, if builds in releases section are lots of taken resources to build it there.
thank you very much at advance!

**Comment by noodlejetski** [comment]
are there any updates about that? the latest version on F-droid is from last year's January, and it doesn't look like there's any other way to get more recent versions outside Play Store.

**Comment by lu-x** [comment]
Latest stable version on Google Play is from 19.11.2021, looks like newer versions are only available on alpha/beta (see https://github.com/AnySoftKeyboard/AnySoftKeyboard#releases) for now.

**Comment by MrRoy** [comment]
FYI - you can download the APK directly from the artifacts on GitHub actions: https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/workflows/deploy.yml

For instance if you want the latest alpha, find one where the `imeMain_alpha_100` action is successful, eg. https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/8753159335
Click on deploy, then the third `Run actions/upload-artifact@v4.3.2`, and click the URL to download the apks.zip

For addons (language packs), it's the same procedure, but with the 
`addOnsMain_alpha_100` action

**Comment by opk12** [comment]
Cross-linking issues related to "make new releases" for ease of searching.

#3974 - Cannot install from Google Play: made for an older Android version
#3906 - F Droid
#3729 - f-droid’s new builds, please!
#3693 - It has been almost a year since last beta release 1.11.582 (September 22, 2022), is this project dead?

Somehow related
#3617 - Release new version or Make alpha available in github/fdroid [maintainer commented]
#3538 - FDroid Version Realise Clarification [= F-droid is the stable release]
#3534 - All app releases should automatically be published in GH releases page  [maintainer opened]

**Comment by licaon-kter** [comment]
@MrRoy this recipe
```
  - versionName: 1.12.786
    versionCode: 8414
    commit: 8fbb0d9bdc6e8bf794be0cfec04f6a8c5ced18a2
    subdir: ime/app
    gradle:
      - yes
    prebuild:
      - sdkmanager 'build-tools;35.0.0'
      - sed -i -e '/navigation-dynamic-features/d' build.gradle
      - sed -i -e 's/versionCode .*/versionCode $$VERCODE$$/' -e 's/versionName .*/versionName
        "$$VERSION$$"/' ../../gradle/versioning_apk.gradle
    scanignore:
      - addons/languages/*/pack/dictionary/*.gz
    ndk: 27.2.12479018
```

builds fine, and runs fine 😄 

but I'm forcing versionName and Code, as I needed to download APKS from https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/12721069078 and find their exact values

how are these calculated? 

when is the next release coming?
